---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: remnawave
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.5.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    controllers:
      remnawave:
        forceRename: remnawave
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: remnawave/backend
              tag: 2.4.4
            env:
              DATABASE_URL:
                valueFrom:
                  secretKeyRef:
                    name: remnawave-pgsql-pguser-remnawave
                    key: uri
              FRONT_END_DOMAIN: "*"
              SUB_PUBLIC_DOMAIN: "remnawave.glants.xyz/sub"
              REDIS_HOST: remnawave-redis.apps.svc.cluster.local
              REDIS_PORT: 6379
            envFrom:
              - secretRef:
                  name: remnawave-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 25m
                memory: 512Mi
              limits:
                memory: 1Gi

      redis:
        containers:
          redis:
            image:
              repository: ghcr.io/valkey-io/valkey
              tag: 9.0.1
            resources:
              requests:
                cpu: 5m
                memory: 32Mi
              limits:
                memory: 128Mi
      subscription-page:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: remnawave/subscription-page
              tag: 7.0.5
            env:
              REMNAWAVE_PANEL_URL: http://remnawave.apps.svc.cluster.local:3000
              CUSTOM_SUB_PREFIX: sub
              MARZBAN_LEGACY_LINK_ENABLED: true
            envFrom:
              - secretRef:
                  name: remnawave-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 25m
                memory: 512Mi
              limits:
                memory: 1Gi
      bot:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: fr1ngg/remnawave-bedolaga-telegram-bot
              tag: v2.9.4
            env:
              DOCKER_ENV: "true"
              REMNAWAVE_API_URL: http://remnawave.apps.svc.cluster.local:3000
              BOT_RUN_MODE: webhook
              WEBHOOK_URL: https://bot.remnawave.glants.xyz
              WEBHOOK_PATH: /webhook
              WEB_API_ENABLED: true
              WEB_API_HOST: 0.0.0.0
              WEB_API_PORT: 8080
              WEB_API_ALLOWED_ORIGINS: https://bot.remnawave.glants.xyz
              REDIS_URL: "redis://remnawave-redis.apps.svc.cluster.local:6379/1"
              DATABASE_MODE: "auto"
              ADMIN_NOTIFICATIONS_ENABLED: true

              POSTGRES_HOST:
                valueFrom:
                  secretKeyRef:
                    name: remnawave-pgsql-pguser-remnawave-bot
                    key: host
              POSTGRES_PORT:
                valueFrom:
                  secretKeyRef:
                    name: remnawave-pgsql-pguser-remnawave-bot
                    key: port
              POSTGRES_DB:
                valueFrom:
                  secretKeyRef:
                    name: remnawave-pgsql-pguser-remnawave-bot
                    key: dbname
              POSTGRES_USER:
                valueFrom:
                  secretKeyRef:
                    name: remnawave-pgsql-pguser-remnawave-bot
                    key: user
              POSTGRES_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: remnawave-pgsql-pguser-remnawave-bot
                    key: password
            envFrom:
              - secretRef:
                  name: remnawave-bot-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 25m
                memory: 512Mi
              limits:
                memory: 1Gi
    service:
      app:
        forceRename: remnawave
        primary: true
        controller: remnawave
        ports:
          http:
            port: 3000
      redis:
        controller: redis
        ports:
          http:
            port: 6379
      subscription-page:
        controller: subscription-page
        ports:
          http:
            port: 3010
      bot:
        controller: bot
        ports:
          http:
            port: 8080
    ingress:
      app:
        className: external-nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          external-dns.alpha.kubernetes.io/target: ingress.ur30.ru
        hosts:
          - host: access.glants.xyz
            paths:
              - path: /
                service:
                  identifier: subscription-page
                  port: http
          - host: marzban.glants.xyz
            paths:
              - path: /
                service:
                  identifier: subscription-page
                  port: http
        tls:
          - secretName: remnawave-tls
            hosts:
              - access.glants.xyz
              - marzban.glants.xyz
      panel:
        className: external-nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          external-dns.alpha.kubernetes.io/target: ingress.ur30.ru
          nginx.ingress.kubernetes.io/whitelist-source-range: 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12
        hosts:
          - host: remnawave.glants.xyz
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - secretName: remnawave-panel-tls
            hosts:
              - remnawave.glants.xyz
      bot:
        className: external-nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          external-dns.alpha.kubernetes.io/target: ingress.ur30.ru
        hosts:
          - host: bot.remnawave.glants.xyz
            paths:
              - path: /
                service:
                  identifier: bot
                  port: http
        tls:
          - secretName: remnawave-bot-tls
            hosts:
              - bot.remnawave.glants.xyz
