---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: remnawave
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.5.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    controllers:
      remnawave:
        forceRename: remnawave
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: remnawave/backend
              tag: 2.4.4
            env:
              DATABASE_URL:
                valueFrom:
                  secretKeyRef:
                    name: remnawave-pgsql-pguser-remnawave
                    key: uri
              FRONT_END_DOMAIN: "*"
              SUB_PUBLIC_DOMAIN: "*"
              REDIS_HOST: remnawave-redis.apps.svc.cluster.local
              REDIS_PORT: 6379
            envFrom:
              - secretRef:
                  name: remnawave-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 25m
                memory: 512Mi
              limits:
                memory: 1Gi

      redis:
        containers:
          redis:
            image:
              repository: ghcr.io/valkey-io/valkey
              tag: 9.0.1
            resources:
              requests:
                cpu: 5m
                memory: 32Mi
              limits:
                memory: 128Mi
      subscription-page:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: remnawave/subscription-page
              tag: 7.0.5
            env:
              REMNAWAVE_PANEL_URL: http://remnawave.apps.svc.cluster.local:3000
              CUSTOM_SUB_PREFIX: sub
              MARZBAN_LEGACY_LINK_ENABLED: true
            envFrom:
              - secretRef:
                  name: remnawave-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 25m
                memory: 512Mi
              limits:
                memory: 1Gi
    service:
      app:
        forceRename: remnawave
        primary: true
        controller: remnawave
        ports:
          http:
            port: 3000
      redis:
        controller: redis
        ports:
          http:
            port: 6379
      subscription-page:
        controller: subscription-page
        ports:
          http:
            port: 3100

    ingress:
      app:
        className: external-nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          external-dns.alpha.kubernetes.io/target: ingress.ur30.ru
        hosts:
          - host: remnawave.glants.xyz
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
          - host: remnawave.glants.xyz
            paths:
              - path: /sub
                service:
                  identifier: subscription-page
                  port: http
        tls:
          - secretName: remnawave-tls
            hosts:
              - remnawave.glants.xyz
