---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: remnawave
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.5.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    controllers:
      remnawave:
        forceRename: remnawave
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: remnawave/backend
              tag: 2.4.4
            env:
              DATABASE_URL:
                valueFrom:
                  secretKeyRef:
                    name: remnawave-pgsql-pguser-remnawave
                    key: uri
              FRONT_END_DOMAIN: "*"
              SUB_PUBLIC_DOMAIN: "remnawave.glants.xyz/sub"
              REDIS_HOST: remnawave-redis.apps.svc.cluster.local
              REDIS_PORT: 6379
              REDIS_PASSWORD: valkey
              WEBHOOK_ENABLED: "true"
              WEBHOOK_URL: http://remnawave-bot:5000/api/v1/remnawave
            envFrom:
              - secretRef:
                  name: remnawave-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 25m
                memory: 512Mi
              limits:
                memory: 1Gi

      redis:
        containers:
          redis:
            image:
              repository: ghcr.io/valkey-io/valkey
              tag: 9.0.1
            env:
              VALKEY_EXTRA_FLAGS: "--requirepass valkey"
            resources:
              requests:
                cpu: 5m
                memory: 32Mi
              limits:
                memory: 128Mi
      subscription-page:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: remnawave/subscription-page
              tag: 7.0.5
            env:
              REMNAWAVE_PANEL_URL: http://remnawave.apps.svc.cluster.local:3000
              CUSTOM_SUB_PREFIX: sub
              MARZBAN_LEGACY_LINK_ENABLED: true
            envFrom:
              - secretRef:
                  name: remnawave-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 25m
                memory: 512Mi
              limits:
                memory: 1Gi
      bot:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            &bot
            image:
              repository: ghcr.io/snoups/remnashop
              tag: v0.6.4
            env:
              APP_DOMAIN: bot.remnawave.glants.xyz
              APP_HOST: 0.0.0.0
              # Port number for the bot web server.
              APP_PORT: 5000
              REMNAWAVE_HOST: remnawave.apps.svc.cluster.local
              REMNAWAVE_PORT: 3000
              REDIS_HOST: remnawave-redis.apps.svc.cluster.local
              REDIS_PORT: 6379
              REDIS_NAME: 1
              REDIS_PASSWORD: valkey
              APP_LOCALES: ru
              APP_DEFAULT_LOCALE: ru
              BOT_MINI_APP: "false"
              BOT_RESET_WEBHOOK: "false"
              DATABASE_HOST:
                valueFrom:
                  secretKeyRef:
                    name: remnawave-pgsql-pguser-remnawave-bot
                    key: host
              DATABASE_PORT:
                valueFrom:
                  secretKeyRef:
                    name: remnawave-pgsql-pguser-remnawave-bot
                    key: port
              DATABASE_NAME:
                valueFrom:
                  secretKeyRef:
                    name: remnawave-pgsql-pguser-remnawave-bot
                    key: dbname
              DATABASE_USER:
                valueFrom:
                  secretKeyRef:
                    name: remnawave-pgsql-pguser-remnawave-bot
                    key: user
              DATABASE_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: remnawave-pgsql-pguser-remnawave-bot
                    key: password
              REMNAWAVE_WEBHOOK_SECRET:
                valueFrom:
                  secretKeyRef:
                    name: remnawave-secret
                    key: WEBHOOK_SECRET_HEADER
            envFrom:
              - secretRef:
                  name: remnawave-bot-secret
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 25m
                memory: 128Mi
              limits:
                memory: 1Gi
          taskiq-worker:
            <<: *bot
            command:
              - taskiq
            args:
              - worker
              - src.infrastructure.taskiq.worker:worker
              - --tasks-pattern
              - src/infrastructure/taskiq/tasks
              - -fsd
          taskiq-scheduler:
            <<: *bot
            command:
              - taskiq
            args:
              - scheduler
              - src.infrastructure.taskiq.scheduler:scheduler
              - --tasks-pattern
              - src/infrastructure/taskiq/tasks
              - -fsd
    service:
      app:
        forceRename: remnawave
        primary: true
        controller: remnawave
        ports:
          http:
            port: 3000
      redis:
        controller: redis
        ports:
          http:
            port: 6379
      subscription-page:
        controller: subscription-page
        ports:
          http:
            port: 3010
      bot:
        controller: bot
        ports:
          http:
            port: 5000
    ingress:
      app:
        className: external-nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          external-dns.alpha.kubernetes.io/target: ingress.ur30.ru
        hosts:
          - host: access.glants.xyz
            paths:
              - path: /
                service:
                  identifier: subscription-page
                  port: http
          - host: marzban.glants.xyz
            paths:
              - path: /
                service:
                  identifier: subscription-page
                  port: http
        tls:
          - secretName: remnawave-tls
            hosts:
              - access.glants.xyz
              - marzban.glants.xyz
      panel:
        className: external-nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          external-dns.alpha.kubernetes.io/target: ingress.ur30.ru
          nginx.ingress.kubernetes.io/whitelist-source-range: 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12
        hosts:
          - host: remnawave.glants.xyz
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - secretName: remnawave-panel-tls
            hosts:
              - remnawave.glants.xyz
      bot:
        className: external-nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          external-dns.alpha.kubernetes.io/target: ingress.ur30.ru
        hosts:
          - host: bot.remnawave.glants.xyz
            paths:
              - path: /
                service:
                  identifier: bot
                  port: http
        tls:
          - secretName: remnawave-bot-tls
            hosts:
              - bot.remnawave.glants.xyz
    persistence:
      bot-data:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: remnawave-bot-data-v1
        advancedMounts:
          bot:
            app:
              - path: /opt/remnashop/logs
                subPath: logs
              - path: /opt/remnashop/assets
                subPath: data
      logs:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /opt/remnashop/logs
            readOnly: false
