---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mautrix-gmessages-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mautrix-gmessages-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: mautrix-gmessages
