---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# resources:
#   - apps.yaml
#   - infra.yaml
#   - media.yaml
#   - monitoring.yaml
#   - networking.yaml
#   - secret.enc.yaml
#   - smarthome.yaml
#   - www.yaml
