---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: matrix-bridge-telegram
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/subterra/apps/matrix/bridge/telegram
  targetNamespace: matrix
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: false # no flux ks dependents
  dependsOn:
    - name: cluster-apps-external-secrets-stores
    - name: cluster-apps-volsync
    - name: cluster-apps-synapse
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: matrix-bridge-gmessages
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/subterra/apps/matrix/bridge/gmessages
  targetNamespace: matrix
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: false # no flux ks dependents
  dependsOn:
    - name: cluster-apps-external-secrets-stores
    - name: cluster-apps-volsync
    - name: cluster-apps-synapse
