---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./mailu/ks.yaml
  - ./netbox/ks.yaml
  - ./nextcloud/ks.yaml
  - ./vaultwarden/ks.yaml
  - ./paperless/ks.yaml
  - ./zipline/ks.yaml
  - ./ocis/ks.yaml
  - ./teamspeak/ks.yaml
  - ./windmill/ks.yaml
  - ./vikunja/ks.yaml
  - ./karakeep/ks.yaml
  - ./any-sync/ks.yaml
  - ./marzban/ks.yaml
  - ./gitea/ks.yaml
  - ./pasarguard/ks.yaml
