---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
resources:
  - ./clustersecretstore.yaml
  - ./secret.sops.yaml
labels:
  - pairs:
      app.kubernetes.io/name: stores
      app.kubernetes.io/instance: onepassword
      app.kubernetes.io/part-of: external-secrets
