---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: immich-nfs
provisioner: nfs
parameters:
  archiveOnDelete: 'false'
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-nfs
spec:
  storageClassName: immich-nfs
  capacity:
    storage: 1Mi # Size does not matter
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.48.150
    path: /mnt/Storinator/PhotoLibrary
  mountOptions:
    - nfsvers=4.2
    - nconnect=8
    - hard
    - noatime
    - rsize=131072
    - wsize=131072
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-nfs
  namespace: apps
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: immich-nfs
  resources:
    requests:
      storage: 1Mi # Size does not matter
