---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pasarguard
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    defaultPodOptions:
      annotations:
        setGateway: 'true'
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"

    controllers:
      pasarguard:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: pasarguard/panel
              tag: v1.6.1
            env:
              SQLALCHEMY_DATABASE_URL: 'sqlite+aiosqlite:////data/db.sqlite3'
              UVICORN_HOST: 0.0.0.0
              DOCS: "True"
              UVICORN_SSL_CERTFILE: /tls/tls.crt
              UVICORN_SSL_KEYFILE: /tls/tls.key
              XRAY_JSON: /data/xray_config.json
              SUDO_USERNAME:
                valueFrom:
                  secretKeyRef:
                    name: pasarguard-secret
                    key: sudo_username
              SUDO_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: pasarguard-secret
                    key: sudo_password
              TELEGRAM_API_TOKEN:
                valueFrom:
                  secretKeyRef:
                    name: pasarguard-secret
                    key: telegram_api_token
              TELEGRAM_ADMIN_ID:
                valueFrom:
                  secretKeyRef:
                    name: pasarguard-secret
                    key: telegram_admin_id
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi

    service:
      app:
        controller: pasarguard
        ports:
          http:
            port: 8000

    ingress:
      app:
        className: "external-nginx"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          external-dns.alpha.kubernetes.io/target: ingress.ur30.ru
          nginx.ingress.kubernetes.io/backend-protocol: HTTPS
          nginx.ingress.kubernetes.io/whitelist-source-range: 192.168.0.0/16
        hosts:
          - host: access.glants.xyz
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - secretName: pasarguard-tls
            hosts:
              - access.glants.xyz
      sub:
        className: "external-nginx"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          external-dns.alpha.kubernetes.io/target: ingress.ur30.ru
          nginx.ingress.kubernetes.io/backend-protocol: HTTPS
        hosts:
          - host: access.glants.xyz
            paths:
              - path: /sub
                service:
                  identifier: app
                  port: http
        tls:
          - secretName: pasarguard-tls
            hosts:
              - access.glants.xyz
    persistence:
      data:
        existingClaim: pasarguard-data-v1
        advancedMounts:
          pasarguard:
            app:
              - path: /data
      certificate:
        name: pasarguard-tls
        type: secret
        advancedMounts:
          pasarguard:
            app:
              - path: /tls/tls.crt
                subPath: tls.crt
              - path: /tls/tls.key
                subPath: tls.key
