---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname nginx-external
  namespace: flux-system
spec:
  targetNamespace: networking
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: ./kubernetes/berries/apps/networking/ingress-nginx/external
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: false
  dependsOn:
    - name: nginx-shared
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname nginx-internal
  namespace: flux-system
spec:
  targetNamespace: networking
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: ./kubernetes/berries/apps/networking/ingress-nginx/internal
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: false
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname nginx-shared
  namespace: flux-system
spec:
  targetNamespace: networking
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: ./kubernetes/berries/apps/networking/ingress-nginx/shared
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: true
  dependsOn:
    - name: cluster-apps-cert-manager-issuers
