---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # renovate: image=quay.io/prometheus-operator/prometheus-operator type=docker
  - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.59.0/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  # renovate: image=quay.io/prometheus-operator/prometheus-operator type=docker
  - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.59.0/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  # renovate: image=quay.io/prometheus-operator/prometheus-operator type=docker
  - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.59.0/example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  # renovate: image=quay.io/prometheus-operator/prometheus-operator type=docker
  - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.59.0/example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
  # renovate: image=quay.io/prometheus-operator/prometheus-operator type=docker
  - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.59.0/example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  # renovate: image=quay.io/prometheus-operator/prometheus-operator type=docker
  - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.59.0/example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
  # renovate: image=quay.io/prometheus-operator/prometheus-operator type=docker
  - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.59.0/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  # renovate: image=quay.io/prometheus-operator/prometheus-operator type=docker
  - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.59.0/example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
