---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: democratic-csi-secret
  namespace: democratic-csi
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: democratic-csi-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: nas
