---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./externalsecret.yaml
  - ./pvc.yaml
  - ./volsync.yaml
configMapGenerator:
  - name: opencloud-configmap
    files:
      - proxy.yaml=./config/proxy.yaml
      - csp.yaml=./config/csp.yaml
generatorOptions:
  disableNameSuffixHash: true
